# 問 4-10 オレンジ郡の憂鬱

## 追加の説明
- ポートフォリオは10年の期間を維持するために毎年再構築されていると仮定する。
- 借入額は毎年125億ドルで維持していると仮定する。
- オレンジ郡は、その年の初めに確定されていた金利で預金利息を支払うと仮定する。

In [17]:
import numpy as np

### ウォール・ストリートから125億ドルを借りなかった場合

まず、もしウォール・ストリートから125億ドルを借りてこれを長期の確定利付債券に投資する、といったことを行わず、お預かりしている資金75億ドルをそのまま短期金利で増やした場合、6年後は、
\begin{align}
75\times 1.060 \times 1.055 \times 1.050 \times 1.045 \times 1.040 \times 1.060 = 101.4528805290
\end{align}
約101億ドルになる。

In [18]:
75*1.06*1.055*1.05*1.045*1.04*1.06

101.45288052899998

### ウォール・ストリートから125億ドル借りた場合

次に、問題文にある通りウォール・ストリートから借りた125億ドルと合わせた200億ドルを、デュレーションが10で平均利息が8.5%のポートフォリオに投資した場合を考える。

$n$年度初めのポートフォリオの価値を$P(n)$とする。$P(1)=200$

In [19]:
P = np.zeros(7)
P[0] = 200

今、このポートフォリオのデュレーション$D$が$10$なので、その修正デュレーションは
\begin{align}
D_M &= \frac{1}{1+\lambda(n)}D\\
\end{align}
ただし、$\lambda(n)$は第$n$年度におけるこのポートフォリオの平均利率で、$\frac{1}{2}\%$づつ下がり、$2\%$下がったら$2\%$上がる。($\lambda(1)=0.085$)

In [20]:
lam = np.arange(0.085, 0.055, -0.005)
lam[5] = lam[4]+0.02
lam[6] = lam[5]+0.02
lam

array([0.085, 0.08 , 0.075, 0.07 , 0.065, 0.085, 0.105])

また、第$n$年度のウォール・ストリートの証券会社への利息払いの利率を$r(n)$とする。

In [21]:
r = np.arange(0.07, 0.045, -0.005)
r[5] = r[4]+0.02
r

array([0.07 , 0.065, 0.06 , 0.055, 0.05 , 0.07 ])

教科書P.75の(3.5)式より、ポートフォリオの現在価値を$P$とすると、
\begin{align}
D_M &= -\frac{1}{P}\frac{dP}{d\lambda}\\
\\
&\simeq-\frac{1}{P}\frac{\Delta P}{\Delta\lambda}\\
\\
\Delta P &\simeq - P \Delta\lambda D_M\\
\\
&= \frac{- P \Delta\lambda D}{1+\lambda}
\end{align}

したがって、このポートフォリオの$n+1$年後の価値は、$n$年後時点での価値にこの変化とポートフォリオのクーポンを加算し、ウォール・ストリートへの利息払いを引いた値となる。
\begin{align}
P(n+1) &= P(n)+\Delta P+P(n)\lambda(n) - 125r(n) \\
&= P(n)+\frac{- P(n) \Delta\lambda D}{1+\lambda(n)}+P(n)\lambda(n) - 125r(n)
\end{align}

In [22]:
for n in range(6):
    P[n+1] = P[n] + (-P[n]*(lam[n+1]-lam[n])*10)/(1+lam[n]) + P[n]*lam[n] - 125*r[n]
P

array([200.        , 217.46658986, 236.80681473, 258.08159629,
       281.3321957 , 240.5364512 , 207.8935332 ])

（確かに金利が上昇し始めてからポートフォリオの価値が下がり始めてる）

したがって、初年度の収益率は
\begin{align}
\frac{P(2) - P(1)}{P(1)-125} = 23.28\%
\end{align}

In [23]:
(P[1]-P[0])/(P[0]-125)

0.232887864823349

6年後における収益率は
\begin{align}
\frac{P(7) - P(1)}{P(1)-125} = 10.52\%
\end{align}

In [27]:
(P[6]-P[0])/(P[0]-125)

0.10524710939444239