# マーコビッツ・モデル

## (a)

収益率$r_i$の資産への配分比率を$w_i$とおく。
\begin{align}
  {\bf w} = \left[
    \begin{array}{c}
      w_1 \\
      w_2 \\
      w_3
    \end{array}
  \right]
\end{align}

期待収益$\bar r_p$を実現するポートフォリオの分散最小化問題は、教科書P.203より
\begin{align}
\min_{\bf w}\frac{1}{2}&\sum_{i,j}w_iw_j\sigma_{ij}\\
\\
s.t. &\sum_iw_i\bar r_i = \bar r_p\\
&\sum_iw_i=1
\end{align}

ラグランジアン$L$は
\begin{align}
L = \frac{1}{2}&\sum_{i,j}w_iw_j\sigma_{ij} -\lambda\left(\sum_iw_i\bar r_i - \bar r_p\right) - \mu\left(\sum_iw_i-1\right)\\
\\
&= \frac{1}{2}{\bf w}^TV{\bf w} - \lambda({\bf w}^T\bar{\bf r} - \bar r_p) - \mu\left(\sum_iw_i-1\right)\\
\end{align}

\begin{align}
\frac{\partial L}{\partial {\bf w}} = \frac{1}{2}(V + V^T){\bf w} - \lambda\bar{\bf r} - \mu{\bf 1}
\end{align}

$\frac{\partial L}{\partial {\bf w}} = {\bf 0}$を解くと、
\begin{align}
{\bf w}&=\frac{1}{2}(V + V^T)^{-1}(\lambda\bar{\bf r} + \mu{\bf 1})\\
\\
&= \frac{1}{2}\left(\left[
    \begin{array}{ccc}
      2 & 1 & 0 \\
      1 & 2 & 1 \\
      0 & 1 & 2
    \end{array}
  \right] + 
  \left[
    \begin{array}{ccc}
      2 & 1 & 0 \\
      1 & 2 & 1 \\
      0 & 1 & 2
    \end{array}
  \right]^T\right)^{-1}\left(\lambda \left[
    \begin{array}{c}
      0.4 \\
      0.8 \\
      0.8 \\
    \end{array}
  \right] + \mu \left[
    \begin{array}{c}
      1 \\
      1 \\
      1 \\
    \end{array}
  \right]\right)\\
\\
&= \left[
    \begin{array}{c}
      0.1\lambda + 0.5\mu \\
      0.2\lambda  \\
      0.3\lambda + 0.5\mu \\
    \end{array}
  \right]
\end{align}

In [20]:
import numpy as np
V = np.matrix([[2,1,0],[1,2,1],[0,1,2]])
r = np.matrix([[0.4],[0.8],[0.8]])
print(V**-1*r)
print((V**-1).sum(axis = 1))

[[0.1]
 [0.2]
 [0.3]]
[[5.00000000e-01]
 [1.11022302e-16]
 [5.00000000e-01]]


これを制約式の$\sum_iw_i\bar r_i = \bar r_p$と$\sum_iw_i=1$に代入すると、
\begin{align}
  \begin{cases}
    0.4(0.1\lambda + 0.5\mu) + 0.8\times0.2\lambda + 0.8(0.3\lambda + 0.5\mu) = \bar r_p\\
    (0.1\lambda + 0.5\mu) + 0.2\lambda + (0.3\lambda + 0.5\mu) = 1
  \end{cases}\\
\end{align}

\begin{align}
  \begin{cases}
    0.44\lambda + 0.6\mu = \bar r_p\\
    0.6\lambda + \mu = 1
  \end{cases}\\
\end{align}

\begin{align}
  \begin{cases}
    \lambda = 12.5\bar r_p - 7.5 \\
    \mu = -7.5\bar r_p + 5.5
  \end{cases}
\end{align}

In [22]:
A = np.matrix([[0.44,0.6],[0.6,1]])
A **-1

matrix([[12.5, -7.5],
        [-7.5,  5.5]])

よって${\bf w}$を$\bar r_p$を用いて表すと、
\begin{align}
w_1 &= -2.5\bar r_p + 2 \\
w_2 &=  2.5\bar r_p - 1.5\\
w_3 &= 0.5
\end{align}


In [42]:
w = np.matrix([[0.1,0.5],[0.2,0.0],[0.3,0.5]])*A**-1
w 

matrix([[-2.5,  2. ],
        [ 2.5, -1.5],
        [ 0. ,  0.5]])

この時、ポートフォリオ収益率の分散は
\begin{align}
{\bf w}^TV{\bf w} &= 12.5\bar r_p^2 - 15\bar r_p + 5.5\\
\\
&= 12.5(\bar r_p - 0.6)^2 + 10
\end{align}
となるので、これを最小にする$\bar r_p$は$0.6$となる。

In [51]:
print(w[:,0].T*V*w[:,0])
print(w[:,0].T*V*w[:,1] + w[:,1].T*V*w[:,0])
print(w[:,1].T*V*w[:,1])

[[12.5]]
[[-15.]]
[[5.5]]


$\bar r_p=0.6$の時、
\begin{align}
w_1 &= 0.5 \\
w_2 &= 0 \\
w_3 &= 0.5
\end{align}
となる。

## (b)

(a)の途中で出てきた
\begin{align}
{\bf w}=
\left[
  \begin{array}{c}
    0.1\lambda + 0.5\mu \\
    0.2\lambda  \\
    0.3\lambda + 0.5\mu \\
  \end{array}
\right]
\end{align}
に$\lambda=1$,$\mu=0$を代入すると、
\begin{align}
w_1 &= 0.1 \\
w_2 &= 0.2 \\
w_3 &= 0.3 \\
\end{align}
合計が$1$になるよう正規化すると、
\begin{align}
w_1 &= \frac{1}{6} \\
w_2 &= \frac{1}{3} \\
w_3 &= \frac{1}{2} \\
\end{align}

## (c)

教科書P.215の(6.10)式より、
\begin{align}
\sum_{i=1}^3\sigma_{ki}v_i=\bar r_k - r_f
\end{align}
\begin{align}
V{\bf v} &= \bar{\bf r} - r_f{\bf 1}\\
\\
{\bf v} &= V^{-1}(\bar{\bf r} - r_f{\bf 1})\\
&= 
\left[
  \begin{array}{c}
    0 \\
    0.2 \\
    0.2 \\
  \end{array}
\right]
\end{align}

In [53]:
V**-1*(r - 0.2)

matrix([[-2.77555756e-17],
        [ 2.00000000e-01],
        [ 2.00000000e-01]])

正規化して、
\begin{align}
{\bf w} = \left[
  \begin{array}{c}
    0 \\
    0.5 \\
    0.5 \\
  \end{array}
\right]
\end{align}